version: '3.8'

services:
  apache:
    build:
      context: ./docker/apache
    container_name: lamp_apache
    ports:
      - "8080:80"
    volumes:
      - ./docker:/var/www/html
    depends_on:
      - db


  db:
    image: mariadb:10.5
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: scoring_app
      MYSQL_USER: lampuser
      MYSQL_PASSWORD: lamp123
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lamp_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass

volumes:
  db_data:
